#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 21 16:19:30 2019

@author: jonteyh
"""

import PyQt5
import monkdata as m
import dtree
import numpy as np
import pandas as pd
import random
from matplotlib import pyplot as plt
import seaborn as sn
sn.set(style="ticks")



print('Entropy MONK-1: '+str(dtree.entropy(m.monk1)))
print('Entropy MONK-2: '+str(dtree.entropy(m.monk2)))
print('Entropy MONK-3: '+str(dtree.entropy(m.monk3)))